CREATE TABLE llx_lmdbwebsite_subscription (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  ref varchar(64) NOT NULL,
  entity integer DEFAULT 1 NOT NULL,
  fk_soc integer,
  fk_contact integer,
  fk_product integer,
  fk_contrat integer,
  fk_facture_initiale integer,
  fk_facture_rec integer,
  fk_last_facture integer,
  product_ref varchar(128),
  offer_code varchar(32) NOT NULL,
  frequency varchar(16) NOT NULL,
  recurrence_mode varchar(24) NOT NULL,
  amount_ht double(24,8) DEFAULT 0,
  amount_ttc double(24,8) DEFAULT 0,
  currency varchar(3) DEFAULT 'EUR',
  stancer_customer_id varchar(128),
  stancer_initial_payment_id varchar(128),
  stancer_initial_payment_url varchar(2048),
  stancer_last_payment_id varchar(128),
  stancer_card_id varchar(128),
  stancer_sepa_id varchar(128),
  stancer_mandate_id varchar(128),
  payment_status varchar(32),
  status varchar(32) DEFAULT 'draft' NOT NULL,
  onboarding_token varchar(128),
  onboarding_token_expiry datetime,
  onboarding_siret varchar(32),
  onboarding_logo varchar(255),
  next_invoice_date date,
  last_invoice_date date,
  ip_hash varchar(128),
  user_agent varchar(255),
  utm_source varchar(255),
  utm_medium varchar(255),
  utm_campaign varchar(255),
  note_private text,
  fk_user_creat integer,
  fk_user_modif integer,
  datec datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

